version: '3.8'

services:
  server-test:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8080 --settings=server.settings.dev
    volumes:
      - ./server:/usr/src/server/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
  postgres-test:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/POSTGRES/data/
    environment:
      - §x_USER=server
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=server

volumes:
  postgres_data:
